#!/bin/bash
#===================================================================================
# LABADMIN SCRIPT SERVER AGENT CONFIG
#         FILE: config
#  DESCRIPTION: Labadmin script server client agent config variables
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#      LICENSE: GNU General Public License v3.0
#      VERSION: 2024.06
#      CREATED: 22.06.28
#=================================================================================== 

#===============================================================================
#  GLOBAL CONFIG VARIABLES
#===============================================================================
readonly repository=linux						# Server repository name to query scripts
readonly log_path="/var/log/lss-agent"			# File path where save logs
readonly sshaddress="10.119.171.216"			# SSH IP address
readonly sshport="58889"						# SSH port
readonly sshuser="lss-agent"					# SSH username

# Local SSH agent key path for ssh authentication
# CAUTION: after install sample keys are used, pelase consider generate and copy your own keys
# By default first .pk file in agent install path, feel free to set direct path to your key
readonly sshprivatekey_path="${agent_path}"/id_lss-agent.pk"								

