#!/bin/bash
#===================================================================================
# LABADMIN SCRIPT SERVER AGENT INSTALL
#         FILE: install
#  DESCRIPTION: Labadmin script server client agent install script
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#      LICENSE: GNU General Public License v3.0
#      VERSION: 2022.06
#      CREATED: 28.06.2022
#=================================================================================== 

#===============================================================================
#  GLOBAL VARIABLES
#===============================================================================
readonly install_dest="/opt/labadmin-script_server_agent/linux/"	# Destination install directory
readonly install_src="$(dirname "$(readlink -f "$0")")"				# Dont change


#=== FUNCTION ==================================================================
#        NAME: check_root
# DESCRIPTION: check if script is exectued as root
#===============================================================================
function check_root() {
	[ "$UID" -eq 0 ] && return 0
	echo -e "\e[1m\e[31mMust be exec with administrative privileges\e[0m"
	exit 1
}


#===============================================================================
#  AGENT INSTALL
#===============================================================================

# CHECK PRIVILEGES
check_root

# COPY FILES
if [ $(realpath "$install_src") != $(realpath "$install_dest") ]; then
	echo -e "\e[1mCopying files to "$install_dest"\e[0m"
	[ ! -d "$install_dest" ] && mkdir -vp "$install_dest" 
	chmod -R 700 "$install_dest"
	chown -R root:root "$install_dest"
	cp -vr "${install_src}/"* "$install_dest/"
	echo
fi

# CREATING SERVICE
echo -e "\e[1mCreating systemd service: /etc/systemd/system/labadmin-script_server_agent.service\e[0m"
echo '[Unit]
Description=Labadmin Script Server Agent
After=network.target
 
[Service]
Type=simple
ExecStart=bash '"$install_dest/labadmin-script_server_agent"'
Restart=on-failure
StandardOutput=journal
StandardError=jorunal
 
[Install]
WantedBy=multi-user.target' > /etc/systemd/system/labadmin-script_server_agent.service
cat /etc/systemd/system/labadmin-script_server_agent.service

echo -e "\e[1mEnabling service\e[0m"
systemctl daemon-reload
systemctl enable labadmin-script_server_agent.service
systemctl start labadmin-script_server_agent.service
systemctl status labadmin-script_server_agent.service

# CONFIG FILES
echo; echo
echo -e "\e[1mMANUAL STEPS TO COMPLETE INSTALLATION:\e[0m"
echo -e "  * Edit \e[1m${install_dest}/config\e[0m file and set variables to config ssh connection"
echo -e "  * Copy \e[1mssh private\e[0m key to ${install_dest} and config path in config file"
echo -e "  * Set \e[1mpermissions 600\e[0m to private key"
