#!/bin/bash
#===================================================================================
# LABADMIN SCRIPT SERVER AGENT INSTALL
#         FILE: install
#  DESCRIPTION: Labadmin script server client agent install script
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#      LICENSE: GNU General Public License v3.0
#      VERSION: 2024.10
#      CREATED: 2024.10.31
#=================================================================================== 

#===============================================================================
#  GLOBAL VARIABLES
#===============================================================================
readonly install_dest="/opt/labadmin-script_server_agent/linux/"	# Destination install directory
readonly install_src="$(dirname "$(readlink -f "$0")")"				# Dont change


#=== FUNCTION ==================================================================
#        NAME: check_root
# DESCRIPTION: check if script is exectued as root
#===============================================================================
function check_root() {
	[ "$UID" -eq 0 ] && return 0
	echo -e "\e[1m\e[31mMust be exec with administrative privileges\e[0m"
	exit 1
}


#===============================================================================
#  AGENT INSTALL
#===============================================================================

# CHECK PRIVILEGES
check_root

# CHECK INSTALL DIRS


# COPY FILES
if [ "$(realpath "$install_src")" != "$(realpath "$install_dest")" ]; then
	echo -e "\e[1mCopying files to "$install_dest"\e[0m"
	[ ! -d "$install_dest" ] && mkdir -vp "$install_dest" 
	rm -rf "${install_dest}"/* "$install_dest"/.[!.]*
	cp -vr "${install_src}/"* "$install_dest/"
	echo
fi
chmod -R 700 "$install_dest"
chmod 600 "${install_dest}"/*.pk
chown -R root:root "$install_dest"

# CREATING SERVICE
echo -e "\e[1mCreating systemd service: /etc/systemd/system/lss-agent.service\e[0m"
echo '[Unit]
Description=Labadmin Script Server Agent
After=network.target
 
[Service]
Type=simple
ExecStart=bash '"$install_dest/lss-agent"'
Restart=on-failure
StandardOutput=journal
StandardError=jorunal
 
[Install]
WantedBy=multi-user.target' > /etc/systemd/system/lss-agent.service
cat /etc/systemd/system/lss-agent.service

echo
echo -e "\e[1mEnabling service\e[0m"
systemctl daemon-reload
systemctl enable lss-agent.service
systemctl start lss-agent.service
systemctl status lss-agent.service

# CONFIG FILES
echo; echo
echo -e "\e[1mMANUAL STEPS TO COMPLETE INSTALLATION:\e[0m"
echo -e "  * Edit \e[1m${install_dest}/config\e[0m file and set variables to set SSH connection config"
echo -e "  * Generate your own SSH private key (ssh-keygen), copy to \e[1m${install_dest}\e[0m and set \e[1msshprivatekey_path\e[0m in config file"
echo -e "  * Set permissions \e[1m600\e[0m to private key"
echo -e "  * Add SSH server public key to \e[1m/root/.ssh/known_hosts\e[0m file"
