#!/bin/bash
#===================================================================================
# LABADMIN SCRIPT SERVER AGENT INSTALL
#         FILE: install
#  DESCRIPTION: Labadmin script server client agent install script
#
#       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
#      LICENSE: GNU General Public License v3.0
#      VERSION: 2024.10
#      CREATED: 28.06.2022
#=================================================================================== 

#===============================================================================
#  GLOBAL CONFIG VARIABLES
#===============================================================================
readonly agent_path="$(dirname "$(readlink -f "$0")")"					# Agent installed path
readonly url="https://raw.githubusercontent.com/leomarcov/labadmin-script_server_agent/main/linux"


# CHECK ROOT
if [ ! "$UID" -eq 0 ]; then
  echo -e "\e[1m\e[31mMust be exec with administrative privileges\e[0m"
  exit 1
fi

echo -e "\e[1mDownloading script files ...\e[0m"
wget -O "${agent_path}/lss-agent" "${url}/lss-agent"
wget -O "${agent_path}/install" "${url}/install"
wget -O "${agent_path}/config" "${url}/config"
